# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Acronym(Model):
    """Detailed response for the acronyms reading critique.

    :param description: Description of the acronym.
    :type description: str
    :param id: Identifier, used to connect from ReadingCritique.
    :type id: str
    :param instrumentation_id: Identifier for instrumentation used to link
     expansion back to an expansion instance on the server side.
    :type instrumentation_id: str
    :param name: Expanded version of the acronym.
    :type name: str
    :param source: Source ID from which the expansion was extracted.
    :type source: str
    :param source_email: Email from which this acronym was extracted.
    :type source_email: ~microsoft.swagger.codegen.editorservice.models.Email
    :param source_file: File from which this acronym was extracted.
    :type source_file: ~microsoft.swagger.codegen.editorservice.models.File
    :param source_type: Type of external source (e.g. email, file etc.)
    :type source_type: str
    :param type: Type of the concept, e.g. Group, Project, etc.
    :type type: str
    """

    _attribute_map = {
        'description': {'key': 'Description', 'type': 'str'},
        'id': {'key': 'Id', 'type': 'str'},
        'instrumentation_id': {'key': 'InstrumentationId', 'type': 'str'},
        'name': {'key': 'Name', 'type': 'str'},
        'source': {'key': 'Source', 'type': 'str'},
        'source_email': {'key': 'SourceEmail', 'type': 'Email'},
        'source_file': {'key': 'SourceFile', 'type': 'File'},
        'source_type': {'key': 'SourceType', 'type': 'str'},
        'type': {'key': 'Type', 'type': 'str'},
    }

    def __init__(self, description=None, id=None, instrumentation_id=None, name=None, source=None, source_email=None, source_file=None, source_type=None, type=None):
        super(Acronym, self).__init__()
        self.description = description
        self.id = id
        self.instrumentation_id = instrumentation_id
        self.name = name
        self.source = source
        self.source_email = source_email
        self.source_file = source_file
        self.source_type = source_type
        self.type = type
