# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AcronymsResponse(Model):
    """Detailed response for the acronyms reading critique.

    :param transaction_id: Id of the transaction. This is returned by the SQI
     service and represents unique id per request
    :type transaction_id: str
    :param acronyms: List of information about detected acronyms.
    :type acronyms:
     list[~microsoft.swagger.codegen.editorservice.models.Acronym]
    """

    _attribute_map = {
        'transaction_id': {'key': 'TransactionId', 'type': 'str'},
        'acronyms': {'key': 'Acronyms', 'type': '[Acronym]'},
    }

    def __init__(self, transaction_id=None, acronyms=None):
        super(AcronymsResponse, self).__init__()
        self.transaction_id = transaction_id
        self.acronyms = acronyms
