# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .common_response_status_property import CommonResponseStatusProperty


class CheckResponseV1(CommonResponseStatusProperty):
    """Check API V1 response definition.

    :param response_status: Gives information about the completeness of the
     results.
     * Success = 0: All components ran and the results are complete.
     * PartialSuccess = 1: Some of the components ran successfully.
     Other components either failed or timed out. We don't have
     the complete results, but we will return the critiques we have.
     * Error = 2: All components failed or timed out, or there's a problem with
     the profile.
     * Disabled = 3: Controller or Orchestrator disabled.
     . Possible values include: 'Success', 'PartialSuccess', 'Error',
     'Disabled'. Default value: "Success" .
    :type response_status: str or
     ~microsoft.swagger.codegen.editorservice.models.enum
    :param request_id: Unique call identifier piped out from the API input.
    :type request_id: str
    :param checked_spans: Array of checked spans.
    :type checked_spans:
     list[~microsoft.swagger.codegen.editorservice.models.CheckedSpan]
    :param critiques: Array of critiques which contains the error information
     data (not sorted by confidence level).
    :type critiques:
     list[~microsoft.swagger.codegen.editorservice.models.Critique]
    :param metadata: Contains metadata tied to particular document part
     (document, paragraph, etc.)
    :type metadata:
     list[~microsoft.swagger.codegen.editorservice.models.Metadata]
    :param reading_critiques: Array of reading specific critiques.
    :type reading_critiques:
     list[~microsoft.swagger.codegen.editorservice.models.ReadingCritique]
    :param reading_response: Reading scenarios specific response.
    :type reading_response:
     ~microsoft.swagger.codegen.editorservice.models.ReadingResponse
    """

    _validation = {
        'critiques': {'required': True},
    }

    _attribute_map = {
        'response_status': {'key': 'ResponseStatus', 'type': 'str'},
        'request_id': {'key': 'RequestId', 'type': 'str'},
        'checked_spans': {'key': 'CheckedSpans', 'type': '[CheckedSpan]'},
        'critiques': {'key': 'Critiques', 'type': '[Critique]'},
        'metadata': {'key': 'Metadata', 'type': '[Metadata]'},
        'reading_critiques': {'key': 'ReadingCritiques', 'type': '[ReadingCritique]'},
        'reading_response': {'key': 'ReadingResponse', 'type': 'ReadingResponse'},
    }

    def __init__(self, critiques, response_status="Success", request_id=None, checked_spans=None, metadata=None, reading_critiques=None, reading_response=None):
        super(CheckResponseV1, self).__init__(response_status=response_status)
        self.request_id = request_id
        self.checked_spans = checked_spans
        self.critiques = critiques
        self.metadata = metadata
        self.reading_critiques = reading_critiques
        self.reading_response = reading_response
