# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CheckedSpan(Model):
    """Representation of a span of checked text.

    :param start: Start index of the checked span. Default value: 0 .
    :type start: int
    :param length: Length of the checked span. Default value: 0 .
    :type length: int
    """

    _validation = {
        'start': {'required': True},
        'length': {'required': True},
    }

    _attribute_map = {
        'start': {'key': 'Start', 'type': 'int'},
        'length': {'key': 'Length', 'type': 'int'},
    }

    def __init__(self, start=0, length=0):
        super(CheckedSpan, self).__init__()
        self.start = start
        self.length = length
