# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .common_app_version_property import CommonAppVersionProperty


class ClientSuggestion(CommonAppVersionProperty):
    """Suggestions passed from the client to the server.

    :param app_version: Version of the calling application.
    :type app_version: str
    :param start: Start index of the critique the suggestion list refers to.
     Default value: 0 .
    :type start: int
    :param length: Length of the critique the suggestion list refers to.
     Default value: 0 .
    :type length: int
    :param suggestions:
    :type suggestions:
     list[~microsoft.swagger.codegen.editorservice.models.Suggestion]
    """

    _attribute_map = {
        'app_version': {'key': 'AppVersion', 'type': 'str'},
        'start': {'key': 'Start', 'type': 'int'},
        'length': {'key': 'Length', 'type': 'int'},
        'suggestions': {'key': 'Suggestions', 'type': '[Suggestion]'},
    }

    def __init__(self, app_version=None, start=0, length=0, suggestions=None):
        super(ClientSuggestion, self).__init__(app_version=app_version)
        self.start = start
        self.length = length
        self.suggestions = suggestions
