# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonRequestIdProperty(Model):
    """CommonRequestIdProperty.

    :param request_id: Unique call identifier generated by the caller (GUID)
    :type request_id: str
    """

    _attribute_map = {
        'request_id': {'key': 'RequestId', 'type': 'str'},
    }

    def __init__(self, request_id=None):
        super(CommonRequestIdProperty, self).__init__()
        self.request_id = request_id
