# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonDescriptorsProperty(Model):
    """CommonDescriptorsProperty.

    :param descriptors: List of descriptors that define the calling
     application instance properties.
    :type descriptors:
     list[~microsoft.swagger.codegen.editorservice.models.Descriptor]
    """

    _attribute_map = {
        'descriptors': {'key': 'Descriptors', 'type': '[Descriptor]'},
    }

    def __init__(self, descriptors=None):
        super(CommonDescriptorsProperty, self).__init__()
        self.descriptors = descriptors
