# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonParagraphRevisionIdProperty(Model):
    """CommonParagraphRevisionIdProperty.

    :param paragraph_revision_id: Number that is changed whenever a paragraph
     is changed. NOTE: This is going to be deprecated -> use more generic
     RevisionId instead.
    :type paragraph_revision_id: str
    """

    _attribute_map = {
        'paragraph_revision_id': {'key': 'ParagraphRevisionId', 'type': 'str'},
    }

    def __init__(self, paragraph_revision_id=None):
        super(CommonParagraphRevisionIdProperty, self).__init__()
        self.paragraph_revision_id = paragraph_revision_id
