# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonLanguageUXIdProperty(Model):
    """CommonLanguageUXIdProperty.

    :param language_ux_id: User current UX language ISO ID. Example: fr-fr for
     French (France) Default: the LanguageId (Not supported yet!)."
    :type language_ux_id: str
    """

    _attribute_map = {
        'language_ux_id': {'key': 'LanguageUXId', 'type': 'str'},
    }

    def __init__(self, language_ux_id=None):
        super(CommonLanguageUXIdProperty, self).__init__()
        self.language_ux_id = language_ux_id
