# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonLanguageIdProperty(Model):
    """CommonLanguageIdProperty.

    :param language_id: Editing language identifier with variants (e.g. en-us,
     en-gb, de-de-1996), see
     http://www.i18nguy.com/unicode/language-identifiers.html
    :type language_id: str
    """

    _attribute_map = {
        'language_id': {'key': 'LanguageId', 'type': 'str'},
    }

    def __init__(self, language_id=None):
        super(CommonLanguageIdProperty, self).__init__()
        self.language_id = language_id
