# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonParagraphIdProperty(Model):
    """CommonParagraphIdProperty.

    :param paragraph_id: Unique identifier of paragraph within a document.
     NOTE: This is going to be deprecated -> use more generic TileId instead.
    :type paragraph_id: str
    """

    _attribute_map = {
        'paragraph_id': {'key': 'ParagraphId', 'type': 'str'},
    }

    def __init__(self, paragraph_id=None):
        super(CommonParagraphIdProperty, self).__init__()
        self.paragraph_id = paragraph_id
