# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonRunOnProfileIdProperty(Model):
    """CommonRunOnProfileIdProperty.

    :param run_on_profile_id: Profile ID assigned by NLX team - please contact
     us for more information. The default is the one selected for the specified
     AppID.
    :type run_on_profile_id: str
    """

    _attribute_map = {
        'run_on_profile_id': {'key': 'RunOnProfileId', 'type': 'str'},
    }

    def __init__(self, run_on_profile_id=None):
        super(CommonRunOnProfileIdProperty, self).__init__()
        self.run_on_profile_id = run_on_profile_id
