# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonTileIdProperty(Model):
    """CommonTileIdProperty.

    :param tile_id: Request: Unique identifier of tile within a document.
     Response: Id of the tile the critique belongs to
    :type tile_id: str
    """

    _attribute_map = {
        'tile_id': {'key': 'TileId', 'type': 'str'},
    }

    def __init__(self, tile_id=None):
        super(CommonTileIdProperty, self).__init__()
        self.tile_id = tile_id
