# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonTextUnitProperty(Model):
    """CommonTextUnitProperty.

    :param text_unit: Unit(s) of text flags:
     * Default = 0x0000, // Default value
     * Word = 0x0001, // Unigram
     * Phrase = 0x0002, // 7-gram
     * Sentence = 0x0004, // Linguistically accurate sentence
     * Paragraph = 0x0008, // Text terminated by paragraph marker(s)
     * Page = 0x0010, // A visible page, slide, equivalent unit.
     * Section = 0x0020, // Section of document/presentation
     * Chapter = 0x0040, // Chapter if such a concept exists in model
     * Document = 0x0100, // Full document contents.
     * RawChars = 0x4000, // Special purpose for scenarios that need raw
     content access
     . Possible values include: 'Default', 'Word', 'Phrase', 'Sentence',
     'Paragraph', 'Page', 'Section', 'Chapter', 'Document', 'RawChars'
    :type text_unit: str or
     ~microsoft.swagger.codegen.editorservice.models.enum
    """

    _attribute_map = {
        'text_unit': {'key': 'TextUnit', 'type': 'str'},
    }

    def __init__(self, text_unit=None):
        super(CommonTextUnitProperty, self).__init__()
        self.text_unit = text_unit
