# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommonRevisionIdProperty(Model):
    """CommonRevisionIdProperty.

    :param revision_id: Request: Number that is changed whenever a tile is
     changed. Response: Revision id of the tile critique belongs to
    :type revision_id: str
    """

    _attribute_map = {
        'revision_id': {'key': 'RevisionId', 'type': 'str'},
    }

    def __init__(self, revision_id=None):
        super(CommonRevisionIdProperty, self).__init__()
        self.revision_id = revision_id
