# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .common_response_status_property import CommonResponseStatusProperty


class ConfigResponseV2(CommonResponseStatusProperty):
    """Config API V2 response definition.

    :param response_status: Gives information about the completeness of the
     results.
     * Success = 0: All components ran and the results are complete.
     * PartialSuccess = 1: Some of the components ran successfully.
     Other components either failed or timed out. We don't have
     the complete results, but we will return the critiques we have.
     * Error = 2: All components failed or timed out, or there's a problem with
     the profile.
     * Disabled = 3: Controller or Orchestrator disabled.
     . Possible values include: 'Success', 'PartialSuccess', 'Error',
     'Disabled'. Default value: "Success" .
    :type response_status: str or
     ~microsoft.swagger.codegen.editorservice.models.enum
    :param critique_category_info_list: A list of CritiqueCategoryInfo, which
     includes critique type information for a particular critique category.
    :type critique_category_info_list:
     list[~microsoft.swagger.codegen.editorservice.models.CritiqueCategoryInfo]
    """

    _validation = {
        'critique_category_info_list': {'required': True},
    }

    _attribute_map = {
        'response_status': {'key': 'ResponseStatus', 'type': 'str'},
        'critique_category_info_list': {'key': 'CritiqueCategoryInfoList', 'type': '[CritiqueCategoryInfo]'},
    }

    def __init__(self, critique_category_info_list, response_status="Success"):
        super(ConfigResponseV2, self).__init__(response_status=response_status)
        self.critique_category_info_list = critique_category_info_list
