# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .common_language_id_property import CommonLanguageIdProperty


class CritiqueTypeOption(CommonLanguageIdProperty):
    """Critique type option.

    :param language_id: Editing language identifier with variants (e.g. en-us,
     en-gb, de-de-1996), see
     http://www.i18nguy.com/unicode/language-identifiers.html
    :type language_id: str
    :param id: Option ID.
    :type id: str
    :param name: Critique option name.
    :type name: str
    :param type_name:
    :type type_name: str
    :param value: The option default value.
    :type value: str
    """

    _validation = {
        'id': {'required': True},
        'value': {'required': True},
    }

    _attribute_map = {
        'language_id': {'key': 'LanguageId', 'type': 'str'},
        'id': {'key': 'Id', 'type': 'str'},
        'name': {'key': 'Name', 'type': 'str'},
        'type_name': {'key': 'TypeName', 'type': 'str'},
        'value': {'key': 'Value', 'type': 'str'},
    }

    def __init__(self, id, value, language_id=None, name=None, type_name=None):
        super(CritiqueTypeOption, self).__init__(language_id=language_id)
        self.id = id
        self.name = name
        self.type_name = type_name
        self.value = value
