# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CritiqueTypeInfo(Model):
    """Critique type option.

    :param id: Critique type ID.
    :type id: str
    :param name: Name of critique type.
    :type name: str
    :param is_binary_critique_type: Whether this option is binary.
    :type is_binary_critique_type: bool
    :param critique_type_values: Valid option values if the option is not
     binary.
    :type critique_type_values: list[str]
    :param default_critique_value: Default value of the option.
    :type default_critique_value: int
    :param critique_priority: Default priority of the critique generated by
     the option.
    :type critique_priority: int
    :param critique_tag: Tag that represents additional info about supported
     features. For example: Consistency support: * None = 0x00, * Consistency =
     0x01:
    :type critique_tag: str
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'default_critique_value': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'Id', 'type': 'str'},
        'name': {'key': 'Name', 'type': 'str'},
        'is_binary_critique_type': {'key': 'IsBinaryCritiqueType', 'type': 'bool'},
        'critique_type_values': {'key': 'CritiqueTypeValues', 'type': '[str]'},
        'default_critique_value': {'key': 'DefaultCritiqueValue', 'type': 'int'},
        'critique_priority': {'key': 'CritiquePriority', 'type': 'int'},
        'critique_tag': {'key': 'CritiqueTag', 'type': 'str'},
    }

    def __init__(self, id, name, default_critique_value, is_binary_critique_type=None, critique_type_values=None, critique_priority=None, critique_tag=None):
        super(CritiqueTypeInfo, self).__init__()
        self.id = id
        self.name = name
        self.is_binary_critique_type = is_binary_critique_type
        self.critique_type_values = critique_type_values
        self.default_critique_value = default_critique_value
        self.critique_priority = critique_priority
        self.critique_tag = critique_tag
