# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Descriptor(Model):
    """Define the calling application instance properties. These cannot usually be
    changed by the user but they are environment specific. Based on these,
    different critique types can be hidden or shown, turned on or off. The
    following descriptors are supported:
    | Name           | Description | Possible values |
    |----------------|-------------|-----------------|
    | Audience       | Indicates the audience for the calling instance | One
    of: DogFood, Microsoft, Production
    | CustomAudience | Indicates the custom audience for the calling instance
    for those caller that do not follow the Office audience standards | e.g.
    MyCustomAudience
    | FlightIds      | Indicates the experiment flights the user is on; the
    flight Ids are separated by ';' | e.g. Flight1;Flight2;FlightN
    | IsCompliant    | Indicates whether the calling application is compliant
    or not | default: False
    | LicenseType    | Indicates the license type of the client user | One of:
    NoLicense, Perpetual, Subscription
    .

    :param name: Name of the descriptor
    :type name: str
    :param value: Value of the descriptor
    :type value: str
    """

    _validation = {
        'name': {'required': True},
        'value': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'Name', 'type': 'str'},
        'value': {'key': 'Value', 'type': 'str'},
    }

    def __init__(self, name, value):
        super(Descriptor, self).__init__()
        self.name = name
        self.value = value
