# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Email(Model):
    """Email metadata where the acronym was originally found.

    :param id: Id of the email.
    :type id: str
    :param subject: Email subject.
    :type subject: str
    :param body: Body (content) of the email.
    :type body: str
    :param sender: Email sender.
    :type sender: str
    :param instrumentation_id: Instrumentation id of this entity.
    :type instrumentation_id: str
    :param snippet: Snippet
    :type snippet: str
    """

    _attribute_map = {
        'id': {'key': 'Id', 'type': 'str'},
        'subject': {'key': 'Subject', 'type': 'str'},
        'body': {'key': 'Body', 'type': 'str'},
        'sender': {'key': 'Sender', 'type': 'str'},
        'instrumentation_id': {'key': 'InstrumentationId', 'type': 'str'},
        'snippet': {'key': 'Snippet', 'type': 'str'},
    }

    def __init__(self, id=None, subject=None, body=None, sender=None, instrumentation_id=None, snippet=None):
        super(Email, self).__init__()
        self.id = id
        self.subject = subject
        self.body = body
        self.sender = sender
        self.instrumentation_id = instrumentation_id
        self.snippet = snippet
