# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .common_response_status_property import CommonResponseStatusProperty


class LanguageInfoResponseV1(CommonResponseStatusProperty):
    """Language Info V1 response definition.

    :param response_status: Gives information about the completeness of the
     results.
     * Success = 0: All components ran and the results are complete.
     * PartialSuccess = 1: Some of the components ran successfully.
     Other components either failed or timed out. We don't have
     the complete results, but we will return the critiques we have.
     * Error = 2: All components failed or timed out, or there's a problem with
     the profile.
     * Disabled = 3: Controller or Orchestrator disabled.
     . Possible values include: 'Success', 'PartialSuccess', 'Error',
     'Disabled'. Default value: "Success" .
    :type response_status: str or
     ~microsoft.swagger.codegen.editorservice.models.enum
    :param supported_languages: List of proofing supported languages the
     client is enabled for.
    :type supported_languages:
     list[~microsoft.swagger.codegen.editorservice.models.SupportedLanguage]
    """

    _validation = {
        'supported_languages': {'required': True},
    }

    _attribute_map = {
        'response_status': {'key': 'ResponseStatus', 'type': 'str'},
        'supported_languages': {'key': 'SupportedLanguages', 'type': '[SupportedLanguage]'},
    }

    def __init__(self, supported_languages, response_status="Success"):
        super(LanguageInfoResponseV1, self).__init__(response_status=response_status)
        self.supported_languages = supported_languages
