# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .common_language_id_property import CommonLanguageIdProperty


class Profile(CommonLanguageIdProperty):
    """Profile information: it contains the critique category info and type
    enabled for the specific profile.

    :param language_id: Editing language identifier with variants (e.g. en-us,
     en-gb, de-de-1996), see
     http://www.i18nguy.com/unicode/language-identifiers.html
    :type language_id: str
    :param id: Profile ID
    :type id: str
    :param title: Display name for a particular Profile.
    :type title: str
    :param default: Indicates in the current is the default profile for the
     calling application.
    :type default: bool
    :param critique_category_info_list: List of critique categories.
    :type critique_category_info_list:
     list[~microsoft.swagger.codegen.editorservice.models.CritiqueCategoryInfo]
    """

    _validation = {
        'id': {'required': True},
        'critique_category_info_list': {'required': True},
    }

    _attribute_map = {
        'language_id': {'key': 'LanguageId', 'type': 'str'},
        'id': {'key': 'Id', 'type': 'str'},
        'title': {'key': 'Title', 'type': 'str'},
        'default': {'key': 'Default', 'type': 'bool'},
        'critique_category_info_list': {'key': 'CritiqueCategoryInfoList', 'type': '[CritiqueCategoryInfo]'},
    }

    def __init__(self, id, critique_category_info_list, language_id=None, title=None, default=None):
        super(Profile, self).__init__(language_id=language_id)
        self.id = id
        self.title = title
        self.default = default
        self.critique_category_info_list = critique_category_info_list
