# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReadingCritique(Model):
    """ReadingCritique.

    :param trace_id: A unique identifier for the critique returned to the
     caller: this is used for the feedback/instrumentation loop.
    :type trace_id: str
    :param type_id: Id of the critique type which generated the critique.
    :type type_id: str
    :param category_title: The title of the critique category.
    :type category_title: str
    :param start: Critique flag start index. Default value: 0 .
    :type start: int
    :param length: Critique flag length. Default value: 0 .
    :type length: int
    :param priority: Error priority level to be shown to the client app which
     will be interpreted as different squiggle colors (or not squiggle):
     * High = 0, // The highest priority (must be fixed). Example: Spelling
     * Medium = 1, // Can be fixed or may not be a problem. Example: Grammar
     * Low = 2, // Can be completely ignored and the content will still be OK..
     Example: Consistency, Style, etc.
     * Informational = 3, // Informational critique, not an error
    :type priority: int
    :param paragraph_id: Unique identifier of paragraph within a document.
     NOTE: This is going to be deprecated -> use more generic TileId instead.
    :type paragraph_id: str
    :param paragraph_revision_id: Number that is changed whenever a paragraph
     is changed. NOTE: This is going to be deprecated -> use more generic
     RevisionId instead.
    :type paragraph_revision_id: str
    :param is_document_level_critique: Indicates whether a critique applies to
     the whole document. It is used to inform user to flash all critiques from
     the same bucket if one changed. Default value: False .
    :type is_document_level_critique: bool
    :param reading_concepts: List of concepts for the critique.
    :type reading_concepts:
     list[~microsoft.swagger.codegen.editorservice.models.ReadingConcept]
    """

    _attribute_map = {
        'trace_id': {'key': 'TraceId', 'type': 'str'},
        'type_id': {'key': 'TypeId', 'type': 'str'},
        'category_title': {'key': 'CategoryTitle', 'type': 'str'},
        'start': {'key': 'Start', 'type': 'int'},
        'length': {'key': 'Length', 'type': 'int'},
        'priority': {'key': 'Priority', 'type': 'int'},
        'paragraph_id': {'key': 'ParagraphId', 'type': 'str'},
        'paragraph_revision_id': {'key': 'ParagraphRevisionId', 'type': 'str'},
        'is_document_level_critique': {'key': 'IsDocumentLevelCritique', 'type': 'bool'},
        'reading_concepts': {'key': 'ReadingConcepts', 'type': '[ReadingConcept]'},
    }

    def __init__(self, trace_id=None, type_id=None, category_title=None, start=0, length=0, priority=None, paragraph_id=None, paragraph_revision_id=None, is_document_level_critique=False, reading_concepts=None):
        super(ReadingCritique, self).__init__()
        self.trace_id = trace_id
        self.type_id = type_id
        self.category_title = category_title
        self.start = start
        self.length = length
        self.priority = priority
        self.paragraph_id = paragraph_id
        self.paragraph_revision_id = paragraph_revision_id
        self.is_document_level_critique = is_document_level_critique
        self.reading_concepts = reading_concepts
