# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReadingResponse(Model):
    """Reading scenarios specific response.

    :param acronyms_response: Detailed response for the acronyms reading
     critique.
    :type acronyms_response:
     ~microsoft.swagger.codegen.editorservice.models.AcronymsResponse
    """

    _attribute_map = {
        'acronyms_response': {'key': 'AcronymsResponse', 'type': 'AcronymsResponse'},
    }

    def __init__(self, acronyms_response=None):
        super(ReadingResponse, self).__init__()
        self.acronyms_response = acronyms_response
