# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TileContent(Model):
    """Content of a tile.

    :param tile_id: Unique Id for the tile within a document.
    :type tile_id: str
    :param revision_id: Tile revision to check.
    :type revision_id: str
    :param analyzer_data: Dictionary that contains additional metadata about a
     tile.
    :type analyzer_data: object
    :param tile_elements: Represents list of all tile elements in the tile.
    :type tile_elements:
     list[~microsoft.swagger.codegen.editorservice.models.TileElement]
    """

    _validation = {
        'tile_id': {'required': True},
        'revision_id': {'required': True},
    }

    _attribute_map = {
        'tile_id': {'key': 'TileId', 'type': 'str'},
        'revision_id': {'key': 'RevisionId', 'type': 'str'},
        'analyzer_data': {'key': 'AnalyzerData', 'type': 'object'},
        'tile_elements': {'key': 'TileElements', 'type': '[TileElement]'},
    }

    def __init__(self, tile_id, revision_id, analyzer_data=None, tile_elements=None):
        super(TileContent, self).__init__()
        self.tile_id = tile_id
        self.revision_id = revision_id
        self.analyzer_data = analyzer_data
        self.tile_elements = tile_elements
