# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Tiling(Model):
    """Dictionary containing arrays of all paragraphs in the document in the
    reading order.

    :param tiling_type: Id of the part of the document the tiling belongs to.
     Possible values include: 'Unknown', 'DocumentText'
    :type tiling_type: str or
     ~microsoft.swagger.codegen.editorservice.models.enum
    :param paragraph_ids: Array of paragraph Ids in reading order
    :type paragraph_ids: list[str]
    :param paragraph_revision_ids: Array of paragraph revision Ids in reading
     order
    :type paragraph_revision_ids: list[str]
    :param number_of_paragraphs_in_tiling: Number of paragraphs in tiling
     (optional)
    :type number_of_paragraphs_in_tiling: int
    """

    _attribute_map = {
        'tiling_type': {'key': 'TilingType', 'type': 'str'},
        'paragraph_ids': {'key': 'ParagraphIds', 'type': '[str]'},
        'paragraph_revision_ids': {'key': 'ParagraphRevisionIds', 'type': '[str]'},
        'number_of_paragraphs_in_tiling': {'key': 'NumberOfParagraphsInTiling', 'type': 'int'},
    }

    def __init__(self, tiling_type=None, paragraph_ids=None, paragraph_revision_ids=None, number_of_paragraphs_in_tiling=None):
        super(Tiling, self).__init__()
        self.tiling_type = tiling_type
        self.paragraph_ids = paragraph_ids
        self.paragraph_revision_ids = paragraph_revision_ids
        self.number_of_paragraphs_in_tiling = number_of_paragraphs_in_tiling
